import { Job } from "@/types";

export const MOCK_JOBS: Job[] = [
  // LinkedIn jobs
  {
    id: "li-001",
    title: "Senior Software Engineer",
    company: "Google",
    location: "Bengaluru, India",
    minExperience: 4,
    maxExperience: 8,
    source: "linkedin",
    applyUrl: "https://linkedin.com/jobs/view/li-001",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Join Google's core engineering team to build scalable distributed systems.",
    skills: ["Go", "Kubernetes", "Distributed Systems", "gRPC"],
    salary: "₹40L – ₹70L / year",
    jobType: "full-time",
    workMode: "hybrid",
    logo: "https://logo.clearbit.com/google.com",
  },
  {
    id: "li-002",
    title: "Product Manager",
    company: "Microsoft",
    location: "Hyderabad, India",
    minExperience: 3,
    maxExperience: 7,
    source: "linkedin",
    applyUrl: "https://linkedin.com/jobs/view/li-002",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Drive product strategy for Microsoft Azure's developer tools ecosystem.",
    skills: ["Product Strategy", "Agile", "Data Analysis", "Azure"],
    salary: "₹35L – ₹60L / year",
    jobType: "full-time",
    workMode: "hybrid",
    logo: "https://logo.clearbit.com/microsoft.com",
  },
  {
    id: "li-003",
    title: "Frontend Developer",
    company: "Flipkart",
    location: "Bengaluru, India",
    minExperience: 2,
    maxExperience: 5,
    source: "linkedin",
    applyUrl: "https://linkedin.com/jobs/view/li-003",
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Build high-performance UIs for Flipkart's e-commerce platform.",
    skills: ["React", "TypeScript", "Redux", "Webpack"],
    salary: "₹18L – ₹30L / year",
    jobType: "full-time",
    workMode: "onsite",
    logo: "https://logo.clearbit.com/flipkart.com",
  },
  {
    id: "li-004",
    title: "Data Scientist",
    company: "Amazon",
    location: "Remote",
    minExperience: 2,
    maxExperience: 6,
    source: "linkedin",
    applyUrl: "https://linkedin.com/jobs/view/li-004",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Develop ML models to optimize Amazon's supply chain and recommendation systems.",
    skills: ["Python", "Machine Learning", "SQL", "AWS SageMaker"],
    salary: "₹30L – ₹55L / year",
    jobType: "full-time",
    workMode: "remote",
    logo: "https://logo.clearbit.com/amazon.com",
  },
  {
    id: "li-005",
    title: "DevOps Engineer",
    company: "Razorpay",
    location: "Bengaluru, India",
    minExperience: 3,
    maxExperience: 6,
    source: "linkedin",
    applyUrl: "https://linkedin.com/jobs/view/li-005",
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Manage CI/CD pipelines and infrastructure for Razorpay's payment platform.",
    skills: ["Kubernetes", "Terraform", "AWS", "Jenkins"],
    salary: "₹22L – ₹40L / year",
    jobType: "full-time",
    workMode: "hybrid",
    logo: "https://logo.clearbit.com/razorpay.com",
  },

  // Naukri jobs
  {
    id: "nk-001",
    title: "Java Backend Developer",
    company: "Infosys",
    location: "Pune, India",
    minExperience: 1,
    maxExperience: 4,
    source: "naukri",
    applyUrl: "https://naukri.com/job-listings/nk-001",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Work on enterprise Java applications for global banking clients.",
    skills: ["Java", "Spring Boot", "Microservices", "SQL"],
    salary: "₹8L – ₹14L / year",
    jobType: "full-time",
    workMode: "onsite",
    logo: "https://logo.clearbit.com/infosys.com",
  },
  {
    id: "nk-002",
    title: "Software Engineer – Full Stack",
    company: "Wipro",
    location: "Chennai, India",
    minExperience: 0,
    maxExperience: 3,
    source: "naukri",
    applyUrl: "https://naukri.com/job-listings/nk-002",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Build full-stack applications using React and Node.js for enterprise clients.",
    skills: ["React", "Node.js", "MongoDB", "REST APIs"],
    salary: "₹6L – ₹12L / year",
    jobType: "full-time",
    workMode: "hybrid",
    logo: "https://logo.clearbit.com/wipro.com",
  },
  {
    id: "nk-003",
    title: "Product Manager – Growth",
    company: "Meesho",
    location: "Bengaluru, India",
    minExperience: 2,
    maxExperience: 5,
    source: "naukri",
    applyUrl: "https://naukri.com/job-listings/nk-003",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Own growth metrics and drive user acquisition for Meesho's marketplace.",
    skills: ["Growth Hacking", "Analytics", "A/B Testing", "SQL"],
    salary: "₹25L – ₹45L / year",
    jobType: "full-time",
    workMode: "onsite",
    logo: "https://logo.clearbit.com/meesho.com",
  },
  {
    id: "nk-004",
    title: "Python Developer",
    company: "TCS",
    location: "Mumbai, India",
    minExperience: 1,
    maxExperience: 5,
    source: "naukri",
    applyUrl: "https://naukri.com/job-listings/nk-004",
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Develop automation scripts and data pipelines for banking sector clients.",
    skills: ["Python", "Django", "PostgreSQL", "Docker"],
    salary: "₹7L – ₹15L / year",
    jobType: "full-time",
    workMode: "onsite",
    logo: "https://logo.clearbit.com/tcs.com",
  },
  {
    id: "nk-005",
    title: "React Native Developer",
    company: "PhonePe",
    location: "Bengaluru, India",
    minExperience: 2,
    maxExperience: 5,
    source: "naukri",
    applyUrl: "https://naukri.com/job-listings/nk-005",
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Build cross-platform mobile features for PhonePe's payment super-app.",
    skills: ["React Native", "JavaScript", "Redux", "iOS", "Android"],
    salary: "₹20L – ₹35L / year",
    jobType: "full-time",
    workMode: "hybrid",
    logo: "https://logo.clearbit.com/phonepe.com",
  },

  // Instahyre jobs
  {
    id: "ih-001",
    title: "Machine Learning Engineer",
    company: "Swiggy",
    location: "Remote",
    minExperience: 3,
    maxExperience: 7,
    source: "instahyre",
    applyUrl: "https://instahyre.com/jobs/ih-001",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Build real-time ML systems for food delivery ETA prediction and personalization.",
    skills: ["Python", "TensorFlow", "Spark", "Kafka"],
    salary: "₹35L – ₹60L / year",
    jobType: "full-time",
    workMode: "remote",
    logo: "https://logo.clearbit.com/swiggy.com",
  },
  {
    id: "ih-002",
    title: "Backend Engineer – Go",
    company: "Zepto",
    location: "Mumbai, India",
    minExperience: 2,
    maxExperience: 5,
    source: "instahyre",
    applyUrl: "https://instahyre.com/jobs/ih-002",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Engineer high-throughput backend services for 10-minute grocery delivery.",
    skills: ["Go", "PostgreSQL", "Redis", "gRPC"],
    salary: "₹25L – ₹45L / year",
    jobType: "full-time",
    workMode: "onsite",
    logo: "https://logo.clearbit.com/zeptonow.com",
  },
  {
    id: "ih-003",
    title: "UX Designer",
    company: "CRED",
    location: "Bengaluru, India",
    minExperience: 2,
    maxExperience: 5,
    source: "instahyre",
    applyUrl: "https://instahyre.com/jobs/ih-003",
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Craft premium user experiences for CRED's fintech platform.",
    skills: ["Figma", "Prototyping", "User Research", "Design Systems"],
    salary: "₹20L – ₹35L / year",
    jobType: "full-time",
    workMode: "hybrid",
    logo: "https://logo.clearbit.com/cred.club",
  },
  {
    id: "ih-004",
    title: "Engineering Manager",
    company: "Ola",
    location: "Bengaluru, India",
    minExperience: 7,
    maxExperience: 12,
    source: "instahyre",
    applyUrl: "https://instahyre.com/jobs/ih-004",
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Lead a team of 8+ engineers building Ola's mapping and routing infrastructure.",
    skills: ["Team Leadership", "System Design", "Java", "AWS"],
    salary: "₹60L – ₹100L / year",
    jobType: "full-time",
    workMode: "onsite",
    logo: "https://logo.clearbit.com/olacabs.com",
  },
  {
    id: "ih-005",
    title: "Software Engineer – Intern",
    company: "Groww",
    location: "Remote",
    minExperience: 0,
    maxExperience: 1,
    source: "instahyre",
    applyUrl: "https://instahyre.com/jobs/ih-005",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    description: "6-month internship building fintech features for Groww's investment platform.",
    skills: ["Java", "React", "MySQL"],
    salary: "₹40,000 / month",
    jobType: "internship",
    workMode: "remote",
    logo: "https://logo.clearbit.com/groww.in",
  },

  // Indeed jobs
  {
    id: "in-001",
    title: "Cloud Solutions Architect",
    company: "IBM",
    location: "Hyderabad, India",
    minExperience: 6,
    maxExperience: 12,
    source: "indeed",
    applyUrl: "https://indeed.com/jobs/view/in-001",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Design and implement cloud migration strategies for Fortune 500 clients.",
    skills: ["AWS", "Azure", "GCP", "Terraform", "Architecture"],
    salary: "₹45L – ₹80L / year",
    jobType: "full-time",
    workMode: "hybrid",
    logo: "https://logo.clearbit.com/ibm.com",
  },
  {
    id: "in-002",
    title: "QA Automation Engineer",
    company: "Adobe",
    location: "Noida, India",
    minExperience: 2,
    maxExperience: 6,
    source: "indeed",
    applyUrl: "https://indeed.com/jobs/view/in-002",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Automate testing for Adobe Creative Cloud's web applications.",
    skills: ["Selenium", "Cypress", "JavaScript", "CI/CD"],
    salary: "₹12L – ₹22L / year",
    jobType: "full-time",
    workMode: "hybrid",
    logo: "https://logo.clearbit.com/adobe.com",
  },
];
